### ISSUE TITLE
Confusion over relative paths

### ISSUE THREAD

**Issue by breck7** [sagold/FuzzyFilePath#11]
Really like this plugin. One thing I'm struggling to grasp is the relative paths.

Let's say my directory structure looks like this:

```
/fruits/apple.js
/veggies/corn.js
```

Now let's say I'm editing corn.js. If I type "app" then hit the relative auto completion shortcut I'd expect the inserted text to be relative to the current file. So I expect "../fruits/apple.js". Instead I get "/fruits/apple.js".

Is this as designed?

**Comment by sagold** [comment]
Thanks for your Feedback.

Hitting _relative auto completion_ should always insert paths relative from your current file. I probably did not mention explicitly that it has to be called __before the suggestions are displayed__ (the shortcut opens the suggestions window). In your case the suggestions window is already opened. Meaning, the selected [rule](https://github.com/sagold/FuzzyFilePath/wiki/Settings#scopesarray) will determine the path type.

Either adjust the ruleset to your specific needs or start the query by hitting the shortcut for _relative auto completion_.

I hope this helps.
Just let me know if something is missing.

**Comment by breck7** [comment]
Hey @sagold, thanks for the quick reply.

I'm still seeing the path relative to the project root. I've tried many combinations. I'm hitting the default "ctrl+alt+space" shortcut before the suggestions are displayed. I haven't overridden any of the default package or keyboard settings. Is there a different way to trigger relative auto completion without the keyboard shortcut?

Here's a gif of what I'm trying: http://i.imgur.com/3x7lfCo.gif

The first time I try auto autocomplte, the second time I specifically use the relative auto complete shortcut.

Default Keybindings:
```
[
    {
        "keys": ["ctrl+alt+space"],
        "command": "insert_path",
        "args": {
            "type": "relative"
        }
    },

    {
        "keys": ["ctrl+shift+space"],
        "command": "insert_path",
        "args": {
            "type": "absolute"
        }
    },

    {
        "keys": ["alt+enter"],
        "command": "ffp_goto_file"
    }
]
```

**Comment by sagold** [comment]
Hi Breck.

Would you mind to post some more information so that i may reproduce or solve the problem?

- Which Sublime Text Version are you using
- Which OS
- What is the current scope on the given path (alt+super+p)
- What is the content of the following tool, if executed on your path: { "keys": ["alt+y"], "command": "ffp_show_context" }

Thank you for your efforts. The animated gif is very helpful.

**Comment by breck7** [comment]
- Sublime 3083
- Windows 10 (hope this isn't the problem as I'm on a daily build)
- I don't see the ffp_show_context command. And alt+super+p doesn't seem to do anything.

I'll give it a shot on my mac at home and see if it works on there.

Thanks @sagold!

**Comment by fetis** [comment]
It looks like I'm having the same issue. I'm on Windows 7 and Subliime 3083.

When I'm trying to autocomplete filename for `require()` it's always insterted as absolute. Neither `./` nor `../` prefixes don't work.

Here's my config (pretty copied from standard one)
```
      {
          // js - require("") and define([""])
          "scope": "source\\.js.*string",   // 1. ignore if scope at cursor does not match expression (super+alt+p)
          "prefix": ["require", "define"],  // 2. trigger only if: require(<cursor>, define([<cursor>
          // if 1 & 2 are true:
          "auto": true,           // auto suggest filepaths, else only by shorctut
          "extensions": ["js"],       // show only .js files
          "relative": true,
          "base_directory": false,       // insert absolute from the set base directory (above)
          "replace_on_insert": [
            ["\\.js$", ""],         // after insertion, remove .js from path
            ["([^.])\\/index$", "\\1"]    // nodejs will load index.js by default => also remove index
          ]
      },
```

**Comment by sagold** [comment]
Hi breck, hi fetis.

Thank you both for helping me find the problem. Obviously i am neglecting tests on windows. The problem was twofold:

- missing treatment of windows paths
- strange default settings for the require-trigger

Both problems have been fixed, tested and released 3e0e06381dc64b3f69797a6d264a1f9a2ae8a8af. 

I hope you can confirm that this issue is solved.

**Comment by fetis** [comment]
It looks like problem was fixed. But I had to completely remove the plugin and made fresh installation.
Thanks for your work!

**Comment by breck7** [comment]
It works! Thanks @sagold !
