### ISSUE TITLE
User settings doesn't work

### ISSUE THREAD

**Issue by fetis** [sagold/FuzzyFilePath#12]
Hello, again.

I'm trying to make my own trigger for `.nunj` files from Nunjucks with next trigger code
```
          "scope": "jinja",
          "prefix": ["include", "import"],
          "auto": true,
          "extensions": ["nunj"],
          "relative": false,
          "base_directory": false
```

I checked the the current settings via Ctrl+Shift+P FuzzyFilePath: Show current settings and even didn't find any mention of jinja. So it looks like user settings are not applied.

I'm on Windows, Sublime 3083 and FuzzyFilePath 0.2.2

**Comment by sagold** [comment]
Hi fetis.

Did restarting Sublime Text help? Settings should currently be loaded on startup once. I am considering to reimplement updates on change in order to get rid of issue #9

**Comment by sagold** [comment]
The latest patch 6c0bbba0aa86c9081fe9430669c2b63a4f940f2f enables live update for changed user settings. Project settings now work as expected, but will only update on restart or project changes.

**Comment by fetis** [comment]
> Did restarting Sublime Text help?
Yes, I tried but this didn't work. The latest update fixed the problem so it works as expected now. Thank you!
