### ISSUE TITLE
Would be really nice to add typescript and coffeescript file supports

### ISSUE THREAD

**Issue by zmLGBBM** [sagold/FuzzyFilePath#17]
`Typescript` and `CoffeeScript` are two languages that compile to `javascript` and needed file path insert support too.

For example, they all have this `require(...)`. And also, `Typescript` has this

    /// <reference path="..." />

for it's intellisense support.

Hopefully this could be implemented, that would be so helpful.

PS: For more information, see http://www.typescriptlang.org/ and http://coffee-script.org/ .

**Comment by sagold** [comment]
Hi.

You can add the required triggers yourself if you follow the [python tutorial](https://github.com/sagold/FuzzyFilePath/wiki/Tutorial:-Add-support-for-python-packages).

I will post the triggers myself in the coming days and add them to the default scope-list.

**Comment by zmLGBBM** [comment]
@sagold Great! That would be handy!

**Comment by sagold** [comment]
Hi.

The following are proposals for the Typescript triggers

```javascript
{
    // Typescript // <reference path="" />
    "scope": "source\\.ts\\scomment",

    "auto": true,
    "relative": true,
    "base_directory": false,
    "prefix": ["path"],
    "tagName": ["reference"],
    "extensions": ["ts", "js"],
    "replace_on_insert": []
},
{
    // Typescript es6 import from/import "*"
    "scope": "string[^\\s]*\\.ts\\s",

    "auto": true,
    "relative": true,
    "base_directory": false,
    "prefix": ["from", "import"],
    "extensions": ["js", "ts"],
    "replace_on_insert": [
	["(\\.js|\\.ts)$", ""],
	["([^.])\\/index$", "\\1"]
    ]
},
```

and Coffeescript

```javascript
{
	// Coffeescript es6 import from/import "*" and require
	"scope": "string[^\\s]*\\.coffee\\s",

	"auto": true,
	"relative": true,
	"base_directory": false,
	"prefix": ["from", "import", "require"],
	"extensions": ["coffee"],
	"replace_on_insert": []
},
```

There is a minor issue with `// <reference ...`, because sublime does not trigger autocompletion in comments (for me). Hitting autocomplete manually opens the dialog.

Would be great if this is tested in the field, before i add them to the default triggers.

**Comment by zmLGBBM** [comment]
@sagold Great, thanks for the work. Unfortunately I cannot test it for now.

**Comment by sagold** [comment]
The changes are released https://github.com/sagold/FuzzyFilePath/commit/92be02fdaa6b5cceb05d89b49bae74634512bfcc
