### ISSUE TITLE
trigger <script src=""> needs improvement

### ISSUE THREAD

**Issue by sagold** [sagold/FuzzyFilePath#20]
Issue described in https://github.com/sagold/FuzzyFilePath/issues/16

**Comment by sagold** [comment]
Proposal for html triggers

**Comment by sagold** [comment]
The following specific trigger should solve the issues with `script` tag on different language files

```javascript
{
    // html - <script src="..">
    "scope": "string\\.quote.*\\.html",
    "prefix": ["src"],
    "tagName": ["script"],
    "auto": true,
    "base_directory": true,
    "extensions": ["js"],
    "relative": true
}
```

**Comment by zmLGBBM** [comment]
@sagold This ought to be good.

**Comment by sagold** [comment]
The changes are resleased https://github.com/sagold/FuzzyFilePath/commit/92be02fdaa6b5cceb05d89b49bae74634512bfcc
