### ISSUE TITLE
prefix only works if on the same line

### ISSUE THREAD

**Issue by chrishoage** [sagold/FuzzyFilePath#21]
In a project I work on there are AMD modules like so:

``` js
define(
  [
    'foo/bar',
    'bar/baz'
 ],

 function (bar, baz) {
 }
)
```

FFP does not trigger with this style of `define`. I have to write the string on the same line as `define` for it to trigger. I can manually trigger it with the key command, but then my custom replace operation does not fire for the scope. 

This may be difficult to fix, but it is an issue.

**Comment by sagold** [comment]
There are two options that you can do right now
- Extend to your Language file to add a unique scope for the import statements (i.e. `foo/bar`)
- Add a custom shortcut with your required replacements (see the [examples](https://github.com/sagold/FuzzyFilePath/wiki/Keybindings#examples))

I will see what would be possible within the plugin. Parsing multiple lines would be an idea, but performance on auto-completion is critical. The real limitation are the too generic language files, thats why the triggers and parsing of context is required as a workaround.
