### ISSUE TITLE
wrong filepath insertion for paths containing bower_components

### ISSUE THREAD

**Issue by kevin-lin** [sagold/FuzzyFilePath#22]
triggering the autocomplete with ctrl+shift+space shows the correct path in the preview dropdown, but when you press enter, it puts in a path that does not match what I selected.

when I select this
`/static/bower_components/angularUtils-pagination/dirPagination.js`
it turns into this
`/staticangularUtils-pagination/dirPagination`

**Comment by sagold** [comment]
Hi kevin-lin.

I pushed a release yesterday. Have you already updated the plugin? Trying this with the latest settings works as expected. I get `"../static/bower_components/testlib"` inserted as the filepath.

Your result is an older bug in the replacement settings, where `bower_components` gets removed for any paths to `bower_components`. Now, only absolute paths starting with `/bower_components/` get replaced. I suggest you reinstall the plugin and check that your *user settings of FuzzyFilePath` have no entry *scopes*.

**Comment by kevin-lin** [comment]
I just tried it again after reinstalling to the latest build. If I use the relative path option with control + alt + space, it gives me `../staticangularUtils-pagination/dirPagination`

I am currently using v2015.11.15.11.11.00, installed on Sublime Text build 3083, installed with package control

**Comment by sagold** [comment]
You could remove any triggers in the settings having a replacement for `bower_components` which do not start with a `^` like here https://github.com/sagold/FuzzyFilePath/blob/master/FuzzyFilePath.sublime-settings#L147. I will cleanup the list as soon i have some time.

Thanks for your feedback.

**Comment by sagold** [comment]
Alternatively you should be able to overwrite the shortcut with

**Comment by sagold** [comment]
Hi kevin-lin.

I just released the changes to package control: f822927f12c33d0cc77a3953909fd87e017f16a6. Hope this solves the problem.

Regards.
