### ISSUE TITLE
does not work on mac OS

### ISSUE THREAD

**Issue by MxJ24** [sagold/FuzzyFilePath#25]
does not work on mac OS.
The key mapping ctrl+alt+space is  Mac OS X 10.10.x system hot key,
and when I remap it to other key it still doesn't work.
but it works fine on windows 7.

**Comment by sagold** [comment]
Hi MxJ24.

I am using this plugin daily on mac os. There must be a different problem. Did you check the console for log or error statements?

**Comment by MxJ24** [comment]
It works on my another Mac OS, so there is something wrong with my old one.
