### ISSUE TITLE
It doesn't work on windows subl 3083 any more

### ISSUE THREAD

**Issue by MxJ24** [sagold/FuzzyFilePath#29]
It doesn't work on windows subl 3083 any more. because it find the wrong currently working project 
 directory.
By the way, why it always trim the file suffix (.js) in the script tag, even through I have already overwritted the config the *.sublime-project???
![2016-05-26_233836](https://cloud.githubusercontent.com/assets/7246998/15580453/62d176e0-239b-11e6-9434-b54e75f6e412.jpg)

**Comment by sagold** [comment]
Hi.

Unfortunately FuzzyFilePath does currently not support multiple folders within a project. In your case that's `XDoc`, `Dropbox` and `py_workspace`. Thus, only the first listed folder will be used as the project directory. There is already an open issue #13 which asks for this feature. I still hope this will be done before this summer.

Having a folders (physically) in your project would workaround this problem. Maybe even a symlink might to the trick.

Regards.

**Comment by MxJ24** [comment]
I had just figured out the workaround last night. I just adjusted the order of my project folder and it works.
by the way, it seems that the scope "." overwrited the scope configed for <script src=""> tag. (I tested last night)
and there is propose: can we read the index built by sublime and may be no manually building process needed any more.

**Comment by sagold** [comment]
With release v0.3.0 multiple folders are now supported
