### ISSUE TITLE
Autocomplete pallet does not show in css strings

### ISSUE THREAD

**Issue by chrishoage** [sagold/FuzzyFilePath#31]
I have the following scope 

``` js
      {
          // postcss - composes from ""
          // source.postcss meta.property-list.css.postcss string.quoted.single.css.postcss
          "scope": "source.postcss meta.property-list.css.postcss string.quoted.single.css.postcss",
          // *: url
          "prefix": ["from"],

          "auto": true,
          "extensions": ["css"],
          "relative": false,
          "base_directory": true,
          "replace_on_insert": [
            // remove base directory
            ["^\\/js/", ""]
          ]
      },
```

Using the following CSS the autocomplete pallet does not show up. 

```
.even {
  composes: label from 'FormLabel'

  background-color: rgba(0, 0, 0, 0.2);
}
```

Logging shows the following. 

```
FFP  | => 2 completions found
FFP 
```

Hitting `ctrl + space` auto completes the path as expected. 

Using the following settings gets the autocomplete pallet to show up. 

``` js
      {
          // postcss - composes from ""
          // source.postcss meta.property-list.css.postcss string.quoted.single.css.postcss
          "scope": "source.postcss meta.property-list.css.postcss",
          // *: url
          "prefix": ["from"],

          "auto": true,
          "extensions": ["css"],
          "relative": false,
          "base_directory": true,
          "replace_on_insert": [
            // remove base directory
            ["^\\/js/", ""]
          ]
      },
```

I can't figure out why adding `string.quoted.single.css.postcss` keeps the pallet from showing up, but FuzzyFilePath seems to be working for the correct scope, _only_ the pallet is missing.

**Comment by sagold** [comment]
Hi chris.

This is strange. Currently i cannot not test your scope. Replacing the scope with the complete scope of my test project: `source.css meta.property-list.css meta.property-value.css string.quoted.single.css` did work for your `compose`-testcase.

Some wild guesses:

- another scope (lower array index) is matched first
- the scope is not perfectly correct (the "scope"-string is a regex)
- some other auto-complete settings (default or plugin) prevent the pallet to open

You could try

- to place the trigger on top of your list
- escape all regex-variables i.e. "source.postcss" to "source\\.postcss"

Unfortunately im off until the end of august. But i will continue to work on the issues then.

Hope you find a solution to your problem.
Regards.

**Comment by sagold** [comment]
In case you want to debug further

This is where the completions are returned: https://github.com/sagold/FuzzyFilePath/blob/master/FuzzyFilePath.py#L344

And next returned to sublime here
https://github.com/sagold/FuzzyFilePath/blob/master/QueryCompletionListener.py#L34

**Comment by chrishoage** [comment]
Interesting, I wonder if it has to do with the `postcss` syntax that I am using. Thanks for the response, I will investigate further.

**Comment by sagold** [comment]
Hi Chris. Stumbled again over the sublime autocomplete triggers. This might be related to the problem: https://www.granneman.com/webdev/editors/sublime-text/top-features-of-sublime-text/auto-completion-in-sublime-text/. This means you can setup sublime to open the pallet on additional scopes.

The default setting is `"auto_complete_selector": "meta.tag - punctuation.definition.tag.begin, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc"`. Which prevents autocompletion on some syntaxes. Note that you can extend the `auto_complete_triggers` in sublime settings and use multiple characters in its `characters` property.

**Comment by chrishoage** [comment]
Sorry for taking so long to get back to this, I tried messing with `auto_complete_selector` and nothing I did allowed this to work.
