### ISSUE TITLE
How to stop this from messing with my project file?

### ISSUE THREAD

**Issue by evandrocoan** [sagold/FuzzyFilePath#32]
### How to stop this from messing with my project file?

I for now I have to uninstall this package for it, because it is just unacceptable;
Also Know As: there is a setting to disable it writing to my project file?

![image](https://cloud.githubusercontent.com/assets/5332158/18254109/f602b508-7370-11e6-8840-3ecba25a8c9c.png)

**Comment by sagold** [comment]
Hi evandrocoan.

Wondered when this will come up. Until the next release you could use the develop branch. I removed modification of the project settings file in 796f0df2ba5ce015ff261fd0b32cac5f0d6b38dc.

**Comment by evandrocoan** [comment]
@sagold thanks.
