### ISSUE TITLE
Crash on sublimeText 3, build 3126 release 23rd Sep 2016

### ISSUE THREAD

**Issue by jwall149** [sagold/FuzzyFilePath#36]
```Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 634, in on_text_command
    res = callback.on_text_command(v, name, args)
  File "QueryCompletionListener in /Users/tonny/Library/Application Support/Sublime Text 3/Installed Packages/FuzzyFilePath.sublime-package", line 74, in on_text_command
AttributeError: 'module' object has no attribute 'get'```

**Comment by sagold** [comment]
Hi jwall.

See this issue https://github.com/sagold/FuzzyFilePath/issues/34. You have to restart Sublime after updating the package. Problem is, Sublime reloads only Python files that are on the root folder. Thus, the state of this Plugin gets inconsistent after an update. I will consider to move all files to root for the next update.

**Comment by jwall149** [comment]
For some unknown reason, restart doesn't work for me, but a restart + re-install plugin works.

Thanks @sagold for the hard work!

**Comment by sagold** [comment]
Thank you for the Feedback!
