### ISSUE TITLE
Doesn't work in CSS block or HTML script src

### ISSUE THREAD

**Issue by alexilyaev** [sagold/FuzzyFilePath#6]
The suggestions don't work if I trigger them in a `url()` in CSS:

``` js
body {
    background-image: url();
}
```

Neither in HTML as `src` for `script`:

``` js
<script src=""></script>
```

**Comment by sagold** [comment]
Its working in my case. What`s your scope `alt+super+p` inside *url()*? ACs are currently restricted to match the scope like `"meta\\.property.*\\.css"`. Any different syntax files might need some more adjustments.
