### ISSUE TITLE
FuzzyFilePath is unaware for changes outside sublime

### ISSUE THREAD

**Issue by doobleweb** [sagold/FuzzyFilePath#7]
FuzzyFilePath is unaware for changes outside sublime, only restarting sublime or disable - enable the plugin do the trick.

for what it's worth,
here are the very specific steps I make:
1 .open sublime
2. create files outside sublime (in my case, install something with bower)
3 .go to html file and use the auto suggestions in

    <script src="|"></script>

other then that, your plugin is awesome and so do you.

**Comment by sagold** [comment]
Thanks!

Problem is, Sublime Text does not seem offer an event for changes in filesystem. Thus it must be implemented in python which would bring other drawbacks. Project files are cached to prevent a sluggish ui on autocompletion. The cache is updated for open files that lie within the project folder, but are not currently cached. Probably thats not the best strategy. I will look into this.

In the meantime, would a command to update the cache manually be any help?

**Comment by sagold** [comment]
Added and released a command `ffp_update_cache` which rebuilds the cache. Add a command to *Key Bindings -> User* like i.e. `{ "keys": ["super+alt+u"], "command": "ffp_update_cache" }` or execute `window.run_command("ffp_update_cache")` in Sublime`s console to add new files in project.

**Comment by doobleweb** [comment]
FANTASTIC!
Thank you very much!
