### ISSUE TITLE
Prefix in latex

### ISSUE THREAD

**Issue by PeterPablo** [sagold/FuzzyFilePath#8]
I would like to create a scope that triggers on `\input{}`:
```
	"scopes": [
		{
			"scope": "text.tex.latex",
			"extensions": ["tex", "tikz"],
			//"prefix": ["input"],
			"auto": true,
		},
	]
```

This does not work, since `input` is followed by a curly brace and this is unsupported by `FuzzyFilePath`. Would you please consider supporting this as well?

If it matters, I am on Ubuntu with ST3 Build 3080 and the package installed through the package manager.

The above defined scope works, if I comment out the prefix.

(I was wondering, whether defining of `scopes` inside `*.sublime-project` is supported?)

**Comment by sagold** [comment]
Hi Peter.

Just added and released curly braces to query validation: 446c27428c52e27e458bae83be99fd9871ec635a

As for settings in sublime-project. You should be able to duplicate the complete settings object. Goto "Project" | "Edit Project" and add your scopes to

```js
{
    // ...
    "settings": {
        "FuzzyFilePath": {
            "scopes": [ ... ]
        }
    }
}
```

Keep in mind, that this overwrites default- and user-settings for each declared variable. Thus all required scopes should go in here.

Hope this helps. Let me know.

**Comment by PeterPablo** [comment]
Thank you for the prompt update!
Removing the comment in front of `prefix` and saving the `FuzzyFilePath.sublime-settings` results in 
```
Traceback (most recent call last):
  File "FuzzyFilePath in /home/userHome/staff/pploss/.config/sublime-text-3/Installed Packages/FuzzyFilePath.sublime-package", line 44, in update_settings
AttributeError: 'NoneType' object has no attribute 'clear'
reloading Packages/User/FuzzyFilePath.sublime-settings
```
and afterwards completion of file names does not work at all.

If I again comment out that line and save, I again get that error message, though completion works as before.

Furthermore I would like to *only* match specific types of braces, for LaTex that would be curly braches. While entering a newline `\\` I get a dropdown, when `"auto": true` is set.

**Comment by sagold** [comment]
Hi Peter.

Your posted error should actually not occur... I made a change for the next release to prevent a failure on reseting the scope cache. For the moment, restarting Sublime Text after making changes in settings should prevent this error and ensure that your new settings are loaded. Settings are currently not updated without restart, since this would introduce more complexity to the plugin.

Until things work out, filepaths may still be manually triggered by (default)

**Comment by sagold** [comment]
Filed an issue for project settings #9

**Comment by sagold** [comment]
And this might help working around *latex* auto completion https://www.sublimetext.com/forum/viewtopic.php?f=2&t=9459

**Comment by PeterPablo** [comment]
Hi Sascha,
thank you for your suggestions. As you wrote I can get completion working in general. Let's see if I/we can figure out a way to restrict this to some latex commands. I am unfamiliar with the innards of ST3 packages, but in case it matters I am using LaTexTools for triggering compilation (as such probably unrelated) and [LaTex Extended](https://github.com/randy3k/LaTeX-Extended) for the language markup.

Peter

PS: On Linux the default shortcut for determining the scope is `ctrl+alt+shift+p`. On Mac it is `alt+super+p`. 
PPS: Do you have a link at hand that explains why in order to use a literal backslash in a regular expression four backslashes `\\\\` are needed?

**Comment by PeterPablo** [comment]
Could [this](http://stackoverflow.com/questions/21114526/how-can-i-trigger-auto-complete-when-typing-using-auto-complete-triggers) be related?

**Comment by sagold** [comment]
There are some many special characters in regex, i.e. backslashes. Special characters have to be escaped by backslashes, which, in this case, lead to some strange expressions like `\\\\` to match strings like `\\`.

I will try the suggestions for latex autocompletion tomorrow. Thanks for your Feedback.

**Comment by sagold** [comment]
Extending the sublime setting with

```json
"auto_complete_triggers":
	[
		{
	        "characters": "abcdefghijklmnopqrstuvwxyz",
	        "selector": "text.tex.latex"
	    }
	]
```

does open the sublime autocompletion panel for `\latex{"file"}`. I am currently using Sublime 3118.
This should solve this issue.
